name: Supply Status Monitor

on:
  # schedule:
  #   # Run daily at midnight EST (1 AM EDT)
  #   - cron: "0 4 * * *"

  # Allow manual triggering
  workflow_dispatch:

jobs:
  monitor-supplies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run supply status monitor
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          SHEETS_CONFIG: ${{ secrets.SHEETS_CONFIG }}
          LOG_LEVEL: info
        run: |
          echo "Starting supply status monitor..."
          npm start
          echo "Monitor execution completed"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Supply status monitor failed');
