name: Supply Status Monitor

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"

  # Allow manual triggering
  workflow_dispatch:

jobs:
  monitor-supplies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run supply status monitor
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          SHEETS_CONFIG: ${{ secrets.SHEETS_CONFIG }}
          LOG_LEVEL: info
        run: npm start

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            // You can customize this to send failure notifications
            // to a Discord webhook or other notification service
            console.log('Supply status monitor failed');
            console.log('Context:', JSON.stringify(context, null, 2));
